base: "/rds/project/rs2099/rds-rs2099-toxgenomics/rna-seq/"
fasta:
  homo_sapiens: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/human/GRCh38.primary_assembly.genome.fa"
  mus_musculus: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/mouse/GRCm38.primary_assembly.genome.fa"
gtf:
  homo_sapiens: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/human/gencode.v34.annotation.gtf"
  mus_musculus: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/mouse/gencode.vM25.annotation.gtf"
star:
  homo_sapiens: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/human/STAR_gencode"
  mus_musculus: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/mouse/STAR_gencode"
bed:
  homo_sapiens: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/human/hg38_Gencode_V24.bed"
  mus_musculus: "/rds/project/rs2099/rds-rs2099-toxgenomics/shared/mouse/mm10_Gencode_VM18.bed"
